### ISSUE TITLE
JOSS Review

### ISSUE THREAD

**Issue by mcavs** [mdhaber/scipy#82]
Dear @mdhaber,

Your paper is well-written and pretty understandable. But I think it needs a minor addition:
* You mentioned that "A through assessment of the methods, accuracy, and speed of the underlying calculations is available in Wallen et al. (2021a)" in the abstract of the paper. These comparisons may be given as a summary under a new section by highlighting the speed, and the other properties of the proposed version of HSD test, after Sec 2. I think it is difficult to follow on the referenced paper.

* The citation of Wallen et al. (2021a) which is in abstract should be out of the brackets.

Thanks,
Mustafa 

For Reference: [Link to review](https://github.com/openjournals/joss-reviews/issues/4383)

**Comment by mdhaber** [comment]
Thanks @mcavs. I will submit a PR for your review shorty. But to clarify:

> The citation of Wallen et al. (2021a) which is in abstract should be out of the brackets.

Do you mean that the citation in the summary section should not be surrounded by parentheses? That is,
"the underlying calculations is available in (Wallan et al., 2021a),"
should appear instead as
"the underlying calculations is available in Wallan et al., 2021a,"?
If so, I'm not sure how to control how citations appear: in the source, this appears as `[@StudentizedRangeSciPy]`, but it renders as "(Wallan et al., 2021a)". Do you know how to control this? If not, this might be a question for the editor. In some citation styles (e.g. IEEE), citations can be used as though they were a noun in the sentence rather than as a parenthetical note, in which case the citation might be OK as it appears.

**Comment by mcavs** [comment]
Hi @mdhaber,

I am sorry, it's my fault, your usage is correct according to the journal's citation format. 
I withdraw my suggestion regarding this change.

Thanks for asking!

**Comment by mdhaber** [comment]
Thanks @mcavs. In that case, does gh-83 resolve this issue?

**Comment by mcavs** [comment]
I think it is ready to flight, @mdhaber!
